import {mkdir,readFile,writeFile} from 'node:fs/promises'
import path from 'node:path'
import {fileURLToPath} from 'node:url'
import {ALL_PUBLISHED_POSTS_QUERY} from './lib/blog-queries.mjs'
import {sanityQuery} from './lib/sanity-client.mjs'
import {normalizePost} from './lib/blog-normalize.mjs'
import {cleanupGeneratedRoutes} from './lib/blog-cleanup.mjs'
import {escapeAttribute,escapeHtml,safeJson} from './lib/html-utils.mjs'
import {renderPortableText} from './lib/portable-text.mjs'
import {CONNECTION_TEST_ID,SANITY_CONFIG,SITE_ORIGIN} from './lib/sanity-config.mjs'

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')
const blogRoot=path.join(root,'blog')
const manifestPath=path.join(root,'.blog-generated-manifest.json')
const fallbackImage=`${SITE_ORIGIN}/assets/images/group-local-lunch.webp`

async function readManifest(){try{return JSON.parse(await readFile(manifestPath,'utf8'))}catch(error){if(error.code==='ENOENT')return null;throw new Error(`Manifest lama tidak valid: ${error.message}`)}}
const dateLabel=value=>value?new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeZone:'UTC'}).format(new Date(value)):''
const meta=(name,content,property=false)=>`<meta ${property?'property':'name'}="${escapeAttribute(name)}" content="${escapeAttribute(content)}">`
const sharedHead=()=>`<link rel="icon" type="image/png" sizes="377x377" href="/assets/images/favicon-logo-only.png">
  <link rel="apple-touch-icon" href="/assets/images/favicon-logo-only.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/css/variables.css?v=phase2-editorial-4"><link rel="stylesheet" href="/css/style.css?v=phase2-visual-a-1"><link rel="stylesheet" href="/css/editorial.css?v=phase2-editorial-4"><link rel="stylesheet" href="/css/blog-foundation.css?v=sanity-phase-a-1"><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-NVVKFSSN');</script>`
const shell=({head,content})=>`<!doctype html>
<html lang="id">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  ${head}
  ${sharedHead()}
</head>
<body data-page="blog" data-static-blog="true"><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NVVKFSSN" height="0" width="0" style="display:none;visibility:hidden" title="Google Tag Manager"></iframe></noscript><header id="site-header"></header><main id="main-content"><div id="page-root">${content}</div></main><footer id="site-footer"></footer><script src="/data/content.js?v=phase2-revised-2" defer></script><script src="/js/main.js?v=phase2-editorial-4" defer></script></body>
</html>
`
function listingHtml(posts){const title='Blog ConsciousTravel | Cerita Perjalanan Bermakna';const description='Cerita dan panduan berbahasa Indonesia tentang perjalanan yang lebih bermakna bersama ConsciousTravel.';const canonical=`${SITE_ORIGIN}/blog/`;const cards=posts.length?`<div class="blog-grid">${posts.map(post=>`<article class="blog-card">${post.coverImageUrl?`<a href="/blog/${escapeAttribute(post.slug)}/" tabindex="-1"><img src="${escapeAttribute(post.coverImageUrl)}" alt="${escapeAttribute(post.coverImageAlt)}" loading="lazy"></a>`:''}<p class="section-kicker">${escapeHtml(post.category.name)}</p><h2><a href="/blog/${escapeAttribute(post.slug)}/">${escapeHtml(post.title)}</a></h2><p>${escapeHtml(post.excerpt)}</p><p class="blog-meta">${escapeHtml(post.author.name)} · ${escapeHtml(dateLabel(post.publishedAt))}</p></article>`).join('')}</div>`:`<div class="blog-empty"><h2>Segera hadir</h2><p>Cerita dan panduan perjalanan bermakna sedang kami siapkan.</p></div>`;return shell({head:`<title>${escapeHtml(title)}</title>\n  ${meta('description',description)}\n  ${meta('robots','noindex, follow')}\n  <link rel="canonical" href="${canonical}">\n  ${meta('og:type','website',true)}${meta('og:title',title,true)}${meta('og:description',description,true)}${meta('og:url',canonical,true)}${meta('og:image',fallbackImage,true)}`,content:`<section class="blog-hero"><div class="container narrow"><p class="section-kicker">Conscious Travel Journal</p><h1>Cerita untuk Perjalanan yang Lebih Bermakna</h1><p>Inspirasi dan panduan perjalanan dalam Bahasa Indonesia.</p></div></section><section class="section"><div class="container">${cards}</div></section>`})}
function articleHtml(post){const canonical=`${SITE_ORIGIN}/blog/${post.slug}/`;const image=post.ogImageUrl||fallbackImage;const body=renderPortableText(post.body);return shell({head:`<title>${escapeHtml(post.seoTitle)}</title>\n  ${meta('description',post.metaDescription)}\n  ${meta('robots',post.noindex?'noindex, follow':'index, follow')}\n  <link rel="canonical" href="${canonical}">\n  ${meta('og:type','article',true)}${meta('og:title',post.seoTitle,true)}${meta('og:description',post.metaDescription,true)}${meta('og:url',canonical,true)}${meta('og:image',image,true)}${meta('article:published_time',post.publishedAt,true)}${post.updatedAt?meta('article:modified_time',post.updatedAt,true):''}`,content:`<article class="blog-article"><header class="blog-article-header"><div class="container narrow"><p class="section-kicker">${escapeHtml(post.category.name)}</p><h1>${escapeHtml(post.title)}</h1><p class="blog-lead">${escapeHtml(post.excerpt)}</p><p class="blog-meta">${escapeHtml(post.author.name)} · Terbit ${escapeHtml(dateLabel(post.publishedAt))}${post.updatedAt?` · Diperbarui ${escapeHtml(dateLabel(post.updatedAt))}`:''}</p>${post.coverImageUrl?`<img class="blog-cover" src="${escapeAttribute(post.coverImageUrl)}" alt="${escapeAttribute(post.coverImageAlt)}">`:''}</div></header><div class="container blog-prose" data-blog-article-body>${body}</div></article>`})}

async function build(){const raw=await sanityQuery(ALL_PUBLISHED_POSTS_QUERY);if(!Array.isArray(raw))throw new Error('Sanity tidak mengembalikan daftar post.');const posts=raw.map(normalizePost);if(!posts.some(post=>post.id===CONNECTION_TEST_ID))throw new Error('Connection-test post tidak ditemukan pada published perspective.');const slugs=posts.map(post=>post.slug);if(new Set(slugs).size!==slugs.length)throw new Error('Slug artikel duplikat ditemukan.');await mkdir(blogRoot,{recursive:true});const removed=await cleanupGeneratedRoutes(blogRoot,await readManifest(),slugs);await writeFile(path.join(blogRoot,'index.html'),listingHtml(posts.filter(post=>!post.noindex&&!post.isConnectionTest)),'utf8');for(const post of posts){const folder=path.join(blogRoot,post.slug);await mkdir(folder,{recursive:true});await writeFile(path.join(folder,'index.html'),articleHtml(post),'utf8')}const manifest={version:1,projectId:SANITY_CONFIG.projectId,dataset:SANITY_CONFIG.dataset,apiVersion:SANITY_CONFIG.apiVersion,perspective:SANITY_CONFIG.perspective,generatedSlugs:[...slugs].sort(),sourceDocumentIds:posts.map(post=>post.id).sort()};await writeFile(manifestPath,`${safeJson(manifest)}\n`,'utf8');console.log(`Blog build berhasil: /blog/ + ${posts.length} route artikel.`);for(const slug of [...slugs].sort())console.log(`- /blog/${slug}/`);if(removed.length)console.log(`Route stale dihapus: ${removed.join(', ')}`)}
build().catch(error=>{console.error(`Blog build gagal: ${error.message}`);process.exitCode=1})
